"""Schemas for the AI chat endpoint.

These are the stable API contract for POST /api/v1/chat.
Business logic lives in services/chat_service.py.
"""

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Incoming chat request from the client."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Natural-language question about habits, hydration, or notes.",
    )


class EvidenceItem(BaseModel):
    """A single piece of structured evidence supporting the answer.

    The UI can render these as labelled cards alongside the answer text.

    type:  Category of the evidence (e.g. "metric", "note", "habit").
    label: Human-readable label (e.g. "Bottle pickups today", "2026-03-18").
    value: The data value as a string (e.g. "6", "1800 ml", "Felt tired…").
    """

    type: str
    label: str
    value: str


class ChatResponse(BaseModel):
    """Response returned by POST /api/v1/chat.

    answer:    Natural-language answer generated by the LLM, or a safe
               fallback if the data was insufficient.
    intent:    The classified intent of the user's question.
    used_notes: Whether pgvector semantic note search contributed to the answer.
                Downstream consumers (UI, LangGraph) can use this to signal
                that the answer includes fuzzy/approximate data.
    evidence:  Structured facts that were used to build the prompt and answer.
               Empty list if the question was unsupported or data was missing.
    """

    answer: str
    intent: str
    used_notes: bool
    evidence: list[EvidenceItem]
